export const GET_MEAL_INFO = "GET_MEAL_INFO";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const GET_MEAL_REVIEWS = "GET_MEAL_REVIEWS";
export const GET_MEAL_LIST = "GET_MEAL_LIST";
export const GET_BASKET = "GET_BASKET";
export const REMOVE_BASKET_ITEM = "REMOVE_BASKET_ITEM";

// export const userConstants = {
// REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
// REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
// REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
//
// LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
// LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
// LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
//
// LOGOUT: 'USERS_LOGOUT',
//
// }
// export const alertConstants = {
// SUCCESS: 'ALERT_SUCCESS',
//    ERROR: 'ALERT_ERROR',
//    CLEAR: 'ALERT_CLEAR'
//  }
