export const GET_MEAL_INFO = "GET_MEAL_INFO";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const GET_COOK_MEAL_INFO = "GET_COOK_MEAL_INFO";
export const GET_MEAL_REVIEWS = "GET_MEAL_REVIEWS";
export const GET_MEAL_LIST = "GET_MEAL_LIST";
