export const GET_MEAL_INFO = "GET_MEAL_INFO";

export const GET_MEAL_INFO_PENDING = "GET_MEAL_INFO_PENDING";
export const GET_MEAL_INFO_FULFILLED = "GET_MEAL_INFO_FULFILLED";
export const GET_MEAL_INFO_REJECTED = "GET_MEAL_INFO_REJECTED";

export const GET_MEAL_LIST = "GET_MEAL_INFO";

export const GET_MEAL_LIST_PENDING = "GET_MEAL_LIST_PENDING";
export const GET_MEAL_LIST_FULFILLED = "GET_MEAL_LIST_FULFILLED";
export const GET_MEAL_LIST_REJECTED = "GET_MEAL_LIST_REJECTED";

export const ADD_TO_BASKET = "ADD_TO_BASKET";
